# 101 NumPy Exercises for Data Analysis (Python)
#### Questions by Selva Prabhakaran
 The goal of the numpy exercises is to serve as a reference as well as to get you to apply numpy beyond the basics. The questions are of 4 levels of difficulties with L1 being the easiest to L4 being the hardest.

### Difficulty Level: L1

In [1]:
# Q.1 Import numpy as np and print the version number.
import numpy as np
np.__version__

'1.19.2'

In [2]:
# Q.2 Create a 1D array of numbers from 0 to 9
np.arange(0,10,1)

# ans np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Q.3 Create a 3×3 numpy array of all True’s
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
# Q.4 Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]


array([1, 3, 5, 7, 9])

In [18]:
# Q.5 Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1 ] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [39]:
# Q.6 Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = np.where((arr % 2 == 1),-1,arr)
print(out)
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Q.7 Convert a 1D array to a 2D array with 2 rows

np.arange(10).reshape(2,-1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Difficulty Level: L2

In [49]:
# Q. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [62]:
#Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

a = np.array([1,2,3]) 
np.r_[np.repeat(a, 3), np.tile(a, 3)] 
# np.r_ (is used to concatenate any number of array slice along row (first) axis)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [67]:
#Q. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)


array([2, 4])

In [68]:
# Q. From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b) # np.setdiff1d From 'a' remove all of 'b'

array([1, 2, 3, 4])

In [69]:
# Q. Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)


(array([1, 3, 5, 7], dtype=int64),)

In [78]:
# Q. Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >=5) & (a <= 10))
print(a[index])
# or 
index2 = np.where(np.logical_and(a>=5, a<=10))
print(a[index2])
# or 
a[(a >=5) & (a <= 10)]

[ 6  9 10]
[ 6  9 10]


array([ 6,  9, 10])

In [83]:
# Q.15 Convert the function maxx that works on two scalars, to work on two arrays.

# def maxx(x, y):
#     """Get the maximum of two items"""
#     if [x] >= [y]:
#         return [x]
#     else:
#         return [y]

# maxx([1, 5],[2, 6])

In [92]:
#Q.16 Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [99]:
# Q.17 Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
print(arr)

print(arr[[1,0,2],:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [98]:
# Q.18 Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
print(arr)
 
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [107]:
#Q.19 Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [112]:
#Q.20 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

np.random.uniform(5,10, size=(5,3))

array([[5.87308019, 7.96507042, 8.82883636],
       [6.47898794, 7.88858519, 7.19858142],
       [8.50966282, 9.9861928 , 8.5260474 ],
       [7.99857709, 6.19794513, 7.73323662],
       [7.56552631, 6.00178931, 7.40978388]])

### Difficulty Level: L1

In [127]:
#Q.21 Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr[:4])
# OR
np.round(rand_arr,3)

[[0.49  0.07  0.962]
 [0.056 0.232 0.514]
 [0.404 0.931 0.754]
 [0.776 0.517 0.366]]


array([[0.49 , 0.07 , 0.962],
       [0.056, 0.232, 0.514],
       [0.404, 0.931, 0.754],
       [0.776, 0.517, 0.366],
       [0.773, 0.809, 0.388]])

In [154]:
# Q.22 Pretty print rand_arr by suppressing the scientific notation (like 1e10)
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
# rand_arr

np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [156]:
#Q.23 Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [177]:
#Q.24 Print the full numpy array a without truncating.
np.set_printoptions(threshold=6)
a = np.arange(15)
a
np.set_printoptions(threshold=np.sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Difficulty Level: L2

In [192]:
# Q.25 Import the iris dataset keeping the text intact.

iris = np.genfromtxt('iris.data', delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [204]:
# Q.26 Extract the text column species from the 1D iris imported in previous question.

iris_1d = np.genfromtxt('iris.data', delimiter=',', dtype=object)
print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
species[:5]

(150, 5)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [209]:
#Q.27 Convert the 1D iris to 2D array iris_2d by omitting the species text field.
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=(0,1,2,3))
iris_2d[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [217]:
# Q.28 Find the mean, median, standard deviation of iris's sepallength (1st column)
sepallength = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0])
mean = np.mean(sepallength)
median = np.median(sepallength)
std = np.std(sepallength)

print(mean)
print(median)
print(std)

5.843333333333334
5.8
0.8253012917851409


In [220]:
# Q.29 Create a normalized form of iris's sepallength whose values range exactly between 
# 0 and 1 so that the minimum has value 0 and maximum has value 1.
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)
# OR
s = (sepallength - Smin)/sepallength.ptp()
print(s)


[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

# Difficulty Level: L3

In [ ]:
# Q.30 Compute the softmax score of sepallength.
