In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [3]:
np.empty(3)

array([0., 0., 0.])

In [15]:
a = np.linspace(2,10,11, dtype='int')
a

array([ 2,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10])

In [17]:
np.arange(2,10,1)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Q. Extract all odd numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [ ]:
#Q. Replace all odd numbers in arr with -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[]
a